 init_setup()
    turn_mod = 1
    inertial_for_auton.calibrate()
    while inertial_for_auton.is_calibrating():
        sleep(50)
    Intake.set_max_torque(100, PERCENT)
    Intake.set_velocity(100, PERCENT)
    while not (not Auto_color == "bl" and not auto_side == "bl"):
        print(console_format(Auto_color))
        print("VEXcode", end="")
        print(console_format(auto_side))
        wait(5, MSEC)
    if auto_side == "r":
        Set_Drivetrain_Velocity_to__25(60)
        drive_forwards_dist_milimeters(300)
        Turn_target_Degrees_With_Inertial_Helping(20)
        Intake.spin(FORWARD)
        Set_Drivetrain_Velocity_to__25(40)
        drive_forwards_dist_milimeters(800)
        wait(0.5, SECONDS)
        drive_forwards_dist_milimeters(-800)
        Set_Drivetrain_Velocity_to__25(50)
        Turn_To_Heading_heading_input_from_0_359_9(270)
        drive_forwards_dist_milimeters(-834)
        Turn_To_Heading_heading_input_from_0_359_9(180)
        drive_forwards_dist_milimeters(-300)
        Intake.spin(FORWARD)
        TopMotor.spin(REVERSE)
        for repeat_count2 in range(4):
            wait(1, SECONDS)
            TopMotor.spin(FORWARD)
            wait(0.2, SECONDS)
            TopMotor.spin(REVERSE)
            wait(5, MSEC)
